# Generated by Django 4.2.25 on 2025-11-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='电影标题')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='评分')),
                ('date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('poster', models.URLField(blank=True, max_length=255, null=True, verbose_name='海报链接')),
                ('actors', models.CharField(blank=True, max_length=255, null=True, verbose_name='演员表')),
                ('regions', models.CharField(blank=True, max_length=255, null=True, verbose_name='地区')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='类型')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='简介')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影集',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_ID', models.CharField(max_length=32, verbose_name='用户ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='用户密码')),
                ('nickname', models.CharField(max_length=255, verbose_name='用户昵称')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '未知')], default=1, verbose_name='性别')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('registration', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='最后登录时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
